config/routes.rb
Rails.application.routes.draw do
  root "doctors#index"

  resources :users 
  resources :doctors do
    resources :appts, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appt.rb
class Appt < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appts, dependent: :destroy 
  has_many :users, through: :appts

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
has_many :appts, dependent: :destroy
has_many :doctors, through: :appts

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appts_controller.rb
class ApptsController < ApplicationController
  before_action :set_doctor

  def index
    @appt = @doctor.appts.all
  end
  
  def show
  end
  
  def new
    @appt = @doctor.appts.new
  end

  def create
    @appt = @doctor.appts.new(appt_params)
    if appt.save
      redirect_to doctor_appts_path(@doctor)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @appt = @doctor.appts.find(params[:id])
    @appt.destroy
    redirect_to doctor_appts_path(@doctor)
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:doctor_id])
    end

    def appt_params
      params.require(:appt).permit(:time, :user_id)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctor_path(@doctor)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.save
      redirect_to doctors_path
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
    params.require(:doctor).permit(:first_name, :last_name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user =  User.find(params[:id])
    end

    def user_params
    params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appts_helper.rb
module ApptsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appts/edit.html.erb
<h1>Appts#edit</h1>
<p>Find me in app/views/appts/edit.html.erb</p>

app/views/appts/index.html.erb
<h1>Make an Appointment</h1>
<h3><%= link_to "Add Appointment", new_doctor_appt_path(@doctor) %></h3>
<hr />
<%# <h3>Your Appointments</h3>
<ul>
  <% @appts.each do |appt| %>
  <%# <li> %>
    <%# appt.user.time %>
  <%# </li>
  <% end %>
<%# </ul> %>

app/views/appts/new.html.erb
<%# could not figure out the syntax to make the form work. the f.select :user_id %>
<%# is the line that was giving me the error %>

<h1>Make an Appointment</h1>
<%= form_with(model: [@doctor, @appt],local: true, class: "ui form") do |f| %>
  <%= f.label :user %>
  <%= f.select :user_id { |user| [user.full_name, user.id] } %>
  <br />
  <%= f.label :time %>
  <%= f.select :time %>
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
  <% end %>

app/views/appts/show.html.erb
<h1>Appts#show</h1>
<p>Find me in app/views/appts/show.html.erb</p>

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name"%>
  </div>
  
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Surname" %>
  </div>

    <%= f.submit "Update", class: "ui green button inverted" %>
<% end %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<%= link_to "Add a Doctor", new_doctor_path %>
<hr />
<h2><%= @doctors.length <= 0 ? "No Doctors" : "" %></h2>
<ul>
  <% @doctors.each do |doctor| %>
  <li>
    <%= link_to doctor.full_name, doctor_path(doctor) %>
  </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add a Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name"%>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Surname" %>
  </div>

    <%= f.submit "Add", class: "ui green button inverted" %>
<% end %>    

app/views/doctors/show.html.erb
<h1><%= @doctor.full_name %></h1>
<hr />
<br />
<br />
<h3><%= link_to "Appointments", doctor_appts_path(@doctor, class: "ui primary button inverted") %></h3>
<br />
<br />
<br />
<h4>Edit Doctor: <%= link_to @doctor.full_name, edit_doctor_path %></h4>
<h4><%= link_to "Remove Doctor", @doctor, method: :delete, class: "ui red button inverted" %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to "Doctors", doctors_path %>
    </li>
    <li>
      <%= link_to "Add Doctor", new_doctor_path %>
    </li>
    <li>
      <%= link_to "Users", users_path %>
    </li>
    <li>
      <%= link_to "Add User", new_user_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrapptApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Surname" %>
  </div>
  <hr />
    <%= f.submit "Update", class: "ui green button inverted" %>
  <% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to "Add User", new_user_path %>
<hr />
<ul>
    <% @users.each do |user| %>
  <li>
    <%= link_to user.full_name, user %>
  </li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Surname" %>
  </div>
  <hr />
    <%= f.submit "Add", class: "ui green button inverted" %>
  <% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul>
  <% @user.doctors.each do |doctor| %>
  <li>
    <%= link_to doctor.full_name, doctor %> 
  </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to "Edit User", edit_user_path, class: "ui blue button inverted" %>
<%= link_to "Remove User", @user, method: :delete, class: "ui red button inverted" %>